import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background':                  '#fcf8ff',
        'surface':                     '#fcf8ff',
        'surface-bright':              '#fcf8ff',
        'surface-dim':                 '#dcd9e1',
        'surface-container-lowest':    '#ffffff',
        'surface-container-low':       '#f5f2fb',
        'surface-container':           '#f0ecf5',
        'surface-container-high':      '#eae7f0',
        'surface-container-highest':   '#e4e1ea',
        'surface-variant':             '#e4e1ea',
        'surface-tint':                '#5054b2',
        'on-surface':                  '#1b1b21',
        'on-surface-variant':          '#464652',
        'on-background':               '#1b1b21',
        'inverse-surface':             '#303036',
        'inverse-on-surface':          '#f2eff8',
        'outline':                     '#777683',
        'outline-variant':             '#c7c5d4',
        'primary':                     '#323593',
        'primary-container':           '#4a4eac',
        'primary-fixed':               '#e1e0ff',
        'primary-fixed-dim':           '#c0c1ff',
        'on-primary':                  '#ffffff',
        'on-primary-container':        '#cbcbff',
        'on-primary-fixed':            '#04006d',
        'on-primary-fixed-variant':    '#373b99',
        'inverse-primary':             '#c0c1ff',
        'secondary':                   '#ffc145',
        'secondary-container':         '#ffc145',
        'secondary-fixed':             '#ffdea8',
        'secondary-fixed-dim':         '#fabc41',
        'on-secondary':                '#1b1b21',
        'on-secondary-container':      '#6f4e00',
        'on-secondary-fixed':          '#271900',
        'on-secondary-fixed-variant':  '#5e4200',
        'tertiary':                    '#3f4054',
        'tertiary-container':          '#56576d',
        'tertiary-fixed':              '#e1e0fa',
        'tertiary-fixed-dim':          '#c4c4de',
        'on-tertiary':                 '#ffffff',
        'on-tertiary-container':       '#cecee7',
        'on-tertiary-fixed':           '#181a2d',
        'on-tertiary-fixed-variant':   '#44455a',
        'error':                       '#ba1a1a',
        'error-container':             '#ffdad6',
        'on-error':                    '#ffffff',
        'on-error-container':          '#93000a',
      },
      borderRadius: {
        'sm':      '0.5rem',
        DEFAULT:   '1rem',
        'md':      '1.5rem',
        'lg':      '2rem',
        'xl':      '3rem',
        'full':    '9999px',
      },
      spacing: {
        'xs':              '4px',
        'base':            '8px',
        'sm':              '12px',
        'md':              '24px',
        'lg':              '48px',
        'xl':              '80px',
        'gutter':          '24px',
        'margin-mobile':   '16px',
        'margin-desktop':  '64px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm':          ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md':          ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile':['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      animation: {
        'spin-slow':  'spin 1.2s linear infinite',
        'fade-in-up': 'fadeInUp 0.25s ease-out forwards',
        'slide-in':   'slideInRight 0.3s ease-out forwards',
        'slide-out':  'slideOutRight 0.3s ease-in forwards',
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(100%)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        slideOutRight: {
          from: { opacity: '1', transform: 'translateX(0)' },
          to:   { opacity: '0', transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
